#!/bin/bash

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication topoSet
runApplication setsToZones
cp system/setRandomFieldDict_K system/setRandomFieldDict
runApplication setRandomField
mv log.setRandomField log.setRandomField1
cp system/setRandomFieldDict_K_fr system/setRandomFieldDict
runApplication setRandomField
mv log.setRandomField log.setRandomField2
#runApplication  setFields
#runApplication dualSimpleDarcyFoam
runApplication dualRhoDarcyFoam
