#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

restore0Dir

runApplication blockMesh
#runApplication checkMesh

runApplication decomposePar -cellDist

# run simulation
#cp 0/h.org 0/h
#cp 0/C.org 0/C
#cp 0/Utheta.org 0/Utheta

#runApplication rhoDarcyFoam
#mpirun --hostfile machines -np 4 icoFoam -parallel > log &
# mpirun -np 4 rhoDarcyFoam -parallel > log &


# reconstructPar
